library(pkggraph)
pkggraph::init(local = FALSE)
pkgs <- ctv:::.get_pkgs_from_ctv_or_repos("MixedModels")
corepkgs <- ctv:::.get_pkgs_from_ctv_or_repos("MixedModels", coreOnly = TRUE)
n1 <- neighborhood_graph(corepkgs[[1]])
png("nbr_graph.png", width = 900, height = 900)
plot(n1)
dev.off()
if (interactive()) system("eog nbr_graph")
