library(pkggraph)
options(repos = c(CRAN = "https://cloud.r-project.org"))
pkggraph::init(local = FALSE)
pkgs <- ctv:::.get_pkgs_from_ctv_or_repos("MixedModels")
corepkgs <- ctv:::.get_pkgs_from_ctv_or_repos("MixedModels", coreOnly = TRUE)
n1 <- neighborhood_graph(corepkgs[[1]])
png("nbr_graph.png", width = 500, height = 500)
plot(n1)
dev.off()
if (interactive()) system("eog nbr_graph.png")
