---
title: "mixed model troubleshooting"
---

# overview

## categories of warnings

* messages vs warnings vs errors
* convergence (numerical optimization questionable)
* singular fits (model is degenerate)
   * other forms of degeneracy (complete separation etc.)
* model diagnostics issues (model is inappropriate)

# convergence problems

## convergence warnings; non-positive-definite Hessians

* what does this mean?
* modern mixed-model software does some form of non-linear optimization
    * sometimes just the covariance parameters, sometimes fixed + covariance parameters
	* (random-effects parameters are profiled out or estimated in an internal loop)
* at the optimum we should have a gradient of zero and a **positive definite** Hessian
* Hessian:


\newcommand{\jjdiag}[1]{\frac{\partial^2 L}{\partial \beta_{#1}^2}}
\newcommand{\jjoff}[2]{\frac{\partial^2 L}{\partial \beta_{#1} \partial \beta_{#2}}}

\[
\left(
\begin{array}{cccc}
\jjdiag{1} & \jjoff{1}{2} & \jjoff{1}{3} & \ldots \\
\jjoff{2}{1} & \jjdiag{2} & \jjoff{2}{3} & \ldots \\
\jjoff{3}{1} & \jjoff{3}{2} & \jjdiag{3} & \ldots \\
\vdots & \vdots & \vdots & \ddots
\end{array}
\right)
\]


## 

* eigenvalues of the Hessian give curvature in the principal directions (== eigenvectors)

```{r echo = FALSE}
## add picture: curve3d + genrose
cc <- emdbook::curve3d(x^2+y^2+3*x*y, from = c(-1, -1), to = c(1,1),
                 sys3d = "none")
```

**FIXME**: picture

## solutions

* double-check the model definition and data
* scale and center predictor variables
* extract Hessian and see *which* eigenvector(s) is/are associated with the minimal eigenvalue(s)

## diagnostics

* `allFit`
* are parameters close enough?
* what is the distribution of negative log-likelihoods?
* which parameters are unstable?

## singular fits

* more Hessian stuff

## model reduction

* drop terms
* drop correlations
* reduced-rank models

## regularization

* `blme`
* other possibilities?

## complete separation (GLM(M)-specific)

* add priors

## other boundary-type problems (extended GLM(M)-specific)

* zero-inflation
* dispersion parameters (e.g. negative binomial)

